---
cassandra:
  image: cassandra:2.1
  ports:
    - "9042:9042"
    - "9160:9160"
  container_name: cassandra

zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
  container_name: zookeeper

kafka:
  image: wurstmeister/kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: "localhost"
    KAFKA_ADVERTISED_PORT: "9092"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  container_name: kafka
